correct height of cutouts within a layer (fix #8)
Alex9779/IKEA-Samla-Inserts pull request #9
Opened 2021-05-24 21:34 UTC by rdmueller

This small change should end the cutouts for the top layer at the right height.

see #8 for example rendering.

Rendering looks good. Will print a test tomorrow.

2021-05-28 06:12 UTC, Alex9779 commented
Ok got a minute to have a look.
I am also not really happy with the naming, "correct" seems there was something false but this was a decision I made. Initially because for this to work right the cutout height has to be nearly correct.
I would like to see it named like "Top Layer Cutouts", must not be the variable name, and the options "full" and "reduced" maybe (?)

Thanks!

2021-05-28 06:13 UTC, Alex9779 requested changes

2021-05-28 06:13 UTC, Alex9779 commented on IKEA_Samla_Inserts.scad
> +Cutouts = "full"; //["full": full, "correct", correct]
This is placed in the "Layer marking" section, should be moved up before line 28.
Also this gives me three options in the "Customizer": "full", "correct" and "correct", last comma should be a semi-colon?

2021-05-28 12:09 UTC, rdmueller commented on IKEA_Samla_Inserts.scad
> +Cutouts = "full"; //["full": full, "correct", correct]
ups. typo

2021-05-28 12:17 UTC, rdmueller commented
you are right - I was also a bit unsure if "correct" would be a good wording. I will brainstorm a bit about it and come up with a new wording...

2021-05-28 20:01 UTC, rdmueller commented on IKEA_Samla_Inserts.scad
> +Cutouts = "full"; //["full": full, "correct", correct]
fixed this

2021-05-28 20:02 UTC, rdmueller commented
I now switched to the wording "full" and "partial". I think this refelct the situation quite well.
I also renamed everything to TopLayerCutouts as you suggested.

2021-05-31 08:39 UTC, Alex9779 approved these changes

2021-05-31 10:24 UTC, Alex9779 requested changes
Sorry but it seems this simple approach won't work out.
Switching to partial also shrinks the cutouts a little bit:
![Comparison](https://user-images.githubusercontent.com/6394581/120167448-0d10f080-c1fe-11eb-89ad-766ac17097ec.gif)
Hard to see in the animation but it is there.
The problem is the method I use to get the overall shrinkage of the cutouts to the top (also the widening of the box): scaling.
And scaling is calculated over the extrusion length (in this case the height) and a factor (here two factor one for x and one for y).
If you reduce the height and do not modify the factors the shape changes.
I remeber I had that problem initially when trying to just shrink the whole container to get the wall and bottom in one step. I changed then the bottom to be of a different thickness than the walls and so I had to generate it a different way and that problem was gone.
So the cutouts must be extruded the whole height, otherwise you have to adjust the scale factors which I don't think is easy. You could do some math to reduce them.
But I think an approach cutting of the top and regenerate without cutouts would be best.

Suggestion:
```
module Samla_Content(layer, width, depth, height, scale_width, scale_depth, width_handle, depth_handle, width_cutout, depth_cutout, scale_handle, scale_cutout, handle_cutout_height, diameter, diameter2, offset) {
    union() {
        difference() {
            linear_extrude(height=height, scale = [scale_width, scale_depth]) {
                offset(delta=-Addtional_Spacing+offset) Samla_Base(layer, width, depth, height, diameter, width_cutout, scale_cutout);
            }
            Samla_HandleAndCutout(layer, width, depth, height, scale_width, scale_depth, width_handle, depth_handle, width_cutout, depth_cutout, scale_handle, scale_cutout, handle_cutout_height, diameter, diameter2, offset);
        }
        if (Top_Layer_Cutouts == "partial") {
            intersection() {
                translate([0, 0, height-(height-handle_cutout_height)/2+(offset!=0?Bottom_Thickness:0)]) cube([width*scale_width, depth*scale_depth, height-handle_cutout_height], true);
                linear_extrude(height=height, scale = [scale_width, scale_depth]) {
                        offset(delta=-Addtional_Spacing+offset) Samla_Base(layer, width, depth, height, diameter, width_cutout, scale_cutout);
                }
            }
        }
    }
}
```

2021-05-31 10:24 UTC, Alex9779 commented on IKEA_Samla_Inserts.scad
> +TopLayerCutouts = "full"; //["full": full, "partial": partial]
The first line should have spaces like the others.
Variable name should be "Top_Layer_Cutouts", underlines are rendered as spaces in the Customizer.
Also the sub-text seems too long, Customizer can't handle two lines:
![image](https://user-images.githubusercontent.com/6394581/120166451-df777780-c1fc-11eb-9edb-c883506d5b25.png)
Just the last one is displayed...

Suggestion:
```
// Top Layer Cutouts
// full are easier to print (no support needed), partial cutouts let the top layer rest on the handle-cutouts
Top_Layer_Cutouts = "full"; //["full": full, "partial": partial]
````

2021-05-31 11:44 UTC, rdmueller commented
I feared something like that. 
I printed 3 of those top layers for 5L boxes and the handle-cutouts did fit quite nice. I only gave the normal cutouts a bit more depth.
What I also noticed with my solution is that (especially for the normal cutouts) there seems to be a slight gap between the vertical and orizontal plane. Nothing to worry about in my case but not perfect.

2021-05-31 11:46 UTC, rdmueller commented on IKEA_Samla_Inserts.scad
> +TopLayerCutouts = "full"; //["full": full, "partial": partial]
hm. ok. But does the cutomizer work at all? You are speaking of the thingiverse customizer, aren't you? I didn't succeed with it.
Nevertheless, your suggestion is fine. I will fix this.

2021-05-31 11:57 UTC, Alex9779 commented on IKEA_Samla_Inserts.scad
> +TopLayerCutouts = "full"; //["full": full, "partial": partial]
I actually meant the Customizer in OpenSCAD...

2021-05-31 12:02 UTC, Alex9779 commented
> I feared something like that.

Well test my suggestion, no other change needed except the variable definition at the top, with that the partial cutouts don't change compared to full (in any layer).

2021-05-31 12:04 UTC, Alex9779 commented
Basically I am just doing what I described, I create the content again without cutouts, then a box to just get the upper top, slight hack needed to get the Bottom_Thickness right...

2021-05-31 12:05 UTC, Alex9779 commented
Still have to revert what you did in Samla_HandleAndCutout....

2021-05-31 12:06 UTC, rdmueller commented
ok, I applied your suggestion and got a nice rendering. I also sliced it and it seems that there is no gap between horizontal and vertical plane anymore :-) Thanx for your help!

2021-05-31 12:12 UTC, Alex9779 commented
> Still have to revert what you did in Samla_HandleAndCutout....

2021-05-31 12:24 UTC, rdmueller commented
ups. missed that

2021-05-31 12:25 UTC, Alex9779 approved these changes

2021-05-31 12:27 UTC, merged

2021-05-31 12:28 UTC, Alex9779 commented
Thanks for your contribution!